apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rekoni
  name: rekoni
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rekoni
  template:
    metadata:
      labels:
        app: rekoni
    spec:
      containers:
<<<<<<< Updated upstream
        - image: hardcoreeng/rekoni-service:v0.7.307
=======
        - image: hardcoreeng/rekoni-service:v0.7.311
>>>>>>> Stashed changes
          name: rekoni
          env:
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: huly-secret
                  key: SERVER_SECRET
          ports:
            - containerPort: 4004
              hostPort: 4004
              protocol: TCP
          resources:
            limits:
              memory: "500M"
      restartPolicy: Always
